import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  CloudLightning,
  Crosshair,
  Dices,
  Factory,
  Gauge,
  Map,
  Radio,
  ScrollText,
  Target,
  Trophy,
  Wind,
} from "lucide-react";

export type TutorialStep = {
  id: string;
  stage: string;
  title: string;
  subtitle: string;
  icon: LucideIcon;
  coreIdea: string;
  playerAction: string;
  watchSignal: string;
  metaphor: string;
  unlock?: string;
  checkpoints?: string[];
};

export const tutorialSteps: TutorialStep[] = [
  {
    id: "market",
    stage: "Act 0 | Pre-flight",
    title: "Read the market weather",
    subtitle: "Start by reading the field, not by guessing a trade.",
    icon: CloudLightning,
    coreIdea: "Spot is the terrain, IV is weather pressure, liquidity is friction, and event risk is a storm core.",
    playerAction: "Check regime, spot path, IV, liquidity, skew, and event risk before adding legs.",
    watchSignal: "A calm market pays different portfolios than a crash or earnings event.",
    metaphor: "Weather first, machine second.",
    unlock: "Market Weather View",
  },
  {
    id: "parts",
    stage: "Act 1 | Greek Sense Lab",
    title: "Build with option parts",
    subtitle: "You are shaping a risk machine, not choosing quiz answers.",
    icon: Factory,
    coreIdea: "Long calls, short calls, long puts, short puts, stock, and cash each add a force to the book.",
    playerAction: "Drag or click parts into the workshop, then tune strike, expiry, IV, side, and quantity.",
    watchSignal: "Changing one leg should move value, Greeks, payoff, and scenario P&L immediately.",
    metaphor: "Every leg is a gear with a cost and a failure mode.",
    unlock: "Portfolio Builder",
  },
  {
    id: "delta",
    stage: "Act 1 | Greek Sense Lab",
    title: "Delta is the wind",
    subtitle: "Delta tells you how spot movement pushes the portfolio.",
    icon: Wind,
    coreIdea: "Positive Delta wants spot to rise; negative Delta wants spot to fall; neutral Delta resists directional drift.",
    playerAction: "Use Stock Hedge when the Delta arrow gets too one-sided.",
    watchSignal: "After a hedge, the Delta wind arrow should shrink toward the center.",
    metaphor: "Delta is lateral wind on the ship.",
    unlock: "Greek Dashboard",
  },
  {
    id: "gamma-theta-vega",
    stage: "Act 1 | Greek Sense Lab",
    title: "Gamma, Theta, and Vega are tradeoffs",
    subtitle: "The Greeks become useful when you feel their tension.",
    icon: Activity,
    coreIdea: "Gamma is steering sensitivity, Theta is time fuel, and Vega is storm sensitivity.",
    playerAction: "Compare long option books with short premium books across choppy, calm, and storm regimes.",
    watchSignal: "Long Gamma can like movement but often leaks Theta; short Vega can collect premium until weather changes.",
    metaphor: "Spring, fuel leak, and storm sail.",
    unlock: "Greek Dashboard",
  },
  {
    id: "charts",
    stage: "Act 2 | Strategy Forge",
    title: "Look at shape before speed",
    subtitle: "Payoff and scenario charts show where the machine breaks.",
    icon: BarChart3,
    coreIdea: "Payoff shows expiry shape; scenario P&L shows near-term stress from spot and IV shocks.",
    playerAction: "Before pressing Run, check whether your loss zone matches the mission limits.",
    watchSignal: "A pretty current P&L can still hide a bad left tail or vol shock.",
    metaphor: "Do the wind-tunnel test before takeoff.",
    unlock: "Payoff and Scenario Charts",
  },
  {
    id: "run",
    stage: "Act 3 | Market Weather Campaign",
    title: "Run, hedge, adjust",
    subtitle: "The market moves; the book must be driven.",
    icon: Crosshair,
    coreIdea: "Each step updates spot, IV, time, values, Greeks, transaction costs, and risk flags.",
    playerAction: "Use Step, Run, Delta hedge, Buy wing, or add/remove legs when the book leaves the safe zone.",
    watchSignal: "Useful adjustments reduce a specific risk; over-trading just pays friction.",
    metaphor: "Steering matters more than naming the strategy.",
    unlock: "Run controls and Risk Shield",
  },
  {
    id: "replay-risk",
    stage: "v0.2 | Replay discipline",
    title: "Use Replay and Risk Shield after every run",
    subtitle: "v0.2 turns each attempt into evidence instead of a pass/fail screen.",
    icon: Gauge,
    coreIdea: "Transaction cost, risk violations, max drawdown, gamma scalp edge, RV-IV, earnings events, and vol crush explain why a run worked.",
    playerAction: "Scrub the replay timeline after each mission, then compare the Risk Shield with the mission constraints before saving progress.",
    watchSignal: "A green P&L with high drawdown, cost drag, or repeated risk flags is not a clean win.",
    metaphor: "The replay is the flight recorder.",
    unlock: "Replay Panel and Risk Shield",
    checkpoints: [
      "Run the mission at least one step before judging it.",
      "Check Delta, Gamma, Theta, Vega attribution and transaction cost.",
      "Use risk flags to decide whether to hedge, buy a wing, or restart cleaner.",
    ],
  },
  {
    id: "surface",
    stage: "v0.3 | Vol Surface Cartographer",
    title: "Read the Vol Surface Cartographer before surface missions",
    subtitle: "v0.3 moves the game from single-option intuition to a full volatility map.",
    icon: Map,
    coreIdea: "Skew, term structure, surface shock, and vega buckets can hurt a portfolio even when total Vega looks neutral.",
    playerAction: "Scan the surface grid, then look at vega buckets before building calendars, wings, skew trades, or event-vol positions.",
    watchSignal: "If a surface twist changes P&L while total Vega looks small, the exposure is hiding by strike or expiry.",
    metaphor: "Do not fly by one weather station when the whole map is moving.",
    unlock: "Vol Surface Cartographer",
    checkpoints: [
      "Compare ATM, wing, and expiry cells before choosing strikes.",
      "Use vega buckets to spot concentration by maturity.",
      "Stress-test skew and term shocks before pressing Run.",
    ],
  },
  {
    id: "review",
    stage: "v0.2 | Debrief",
    title: "Replay the P&L",
    subtitle: "The score is less important than knowing why it happened.",
    icon: Radio,
    coreIdea: "Debrief splits P&L into Delta, Gamma, Theta, Vega, costs, drawdown, risk flags, and residual.",
    playerAction: "After each mission, ask whether you earned edge or merely survived the path.",
    watchSignal: "If residual or risk flags are large, your mental model missed something.",
    metaphor: "A good trader can explain the scar tissue.",
    unlock: "Replay Panel",
  },
  {
    id: "maker",
    stage: "v0.4 | Market Maker Arena",
    title: "Market making adds adverse selection",
    subtitle: "A quote is a risk price, not a random spread.",
    icon: ScrollText,
    coreIdea: "Client flow can be benign or toxic. Tight quotes win flow but can leave bad inventory.",
    playerAction: "Quote bid/ask, take fills selectively, then manage the Greeks left behind.",
    watchSignal: "If fills always hurt after the next move, the quote was too cheap for the information risk.",
    metaphor: "The spread is payment for inventory and uncertainty.",
    unlock: "Market Maker Arena",
    checkpoints: [
      "Widen quotes when toxicity or event risk rises.",
      "After fills, watch inventory Delta and Vega before accepting more flow.",
      "Treat the spread as compensation for information risk, not free income.",
    ],
  },
  {
    id: "probability",
    stage: "v1.0 | Probability Pit",
    title: "Calibrate probability before chasing score",
    subtitle: "v1.0 adds forecast quality through the Probability Pit and Average Brier score.",
    icon: Target,
    coreIdea: "The game now scores whether your probabilities match outcomes, not just whether a trade made money.",
    playerAction: "Submit forecasts for event paths, RV-IV outcomes, toxic flow, and surface mispricing, then read the Brier feedback.",
    watchSignal: "Overconfident 90% calls that miss will damage calibration faster than modest, well-priced uncertainty.",
    metaphor: "A forecast is a price for belief.",
    unlock: "Probability Pit",
    checkpoints: [
      "Make a probability forecast before running the market path.",
      "Compare your Brier result against the P&L attribution.",
      "Lower confidence when the surface, flow, or event signal is mixed.",
    ],
  },
  {
    id: "seeds",
    stage: "v1.0 | Challenge Seeds",
    title: "Use Challenge seed runs for repeatable practice",
    subtitle: "Seeds turn random procedural missions into shareable drills.",
    icon: Dices,
    coreIdea: "A Challenge seed creates a generated market mission with a stable path, constraints, and scoring target.",
    playerAction: "Launch a seed, play it, replay the failure points, then rerun the same seed with a cleaner construction.",
    watchSignal: "If the same seed keeps failing in the same way, the issue is a risk habit rather than bad luck.",
    metaphor: "A seed is a controlled stress lab.",
    unlock: "Trials, seeds, leaderboard",
    checkpoints: [
      "Start with the default seed, then type your own daily seed.",
      "Save only runs where the replay and risk shield support the score.",
      "Use generated missions to bridge the core 12 levels into the 100+ mission pool.",
    ],
  },
  {
    id: "trials",
    stage: "v1.0 | Jane Street Trials",
    title: "Enter Jane Street Trials only after the loop is stable",
    subtitle: "Trials combine Greeks, surface reading, probability calibration, and market making under tighter limits.",
    icon: Trophy,
    coreIdea: "Jane Street Trials are the capstone: build, quote, hedge, forecast, replay, and defend the score.",
    playerAction: "Select a trial, scan its constraints, build the book, use market-maker fills carefully, submit Probability Pit forecasts, then debrief before saving.",
    watchSignal: "A trial win should have controlled drawdown, clean attribution, acceptable Brier feedback, and limited inventory stress.",
    metaphor: "The capstone is an integrated desk shift.",
    unlock: "Jane Street Trials",
    checkpoints: [
      "Clear Greek Sense Lab and Strategy Forge basics first.",
      "Use Vol Surface Cartographer before surface-sensitive trials.",
      "Save successful trial runs to the leaderboard for score comparison.",
    ],
  },
  {
    id: "v1-route",
    stage: "Tutorial completion route",
    title: "1.0 play-through route",
    subtitle: "This is the recommended route for playing the current build end to end.",
    icon: Trophy,
    coreIdea: "Play the game as one loop: read market, build book, run path, hedge, replay, calibrate, seed, trial, score.",
    playerAction: "Follow the checkpoints below when starting a fresh profile or teaching another player.",
    watchSignal: "You are ready for 1.0 once you can explain a score through P&L attribution, risk flags, surface exposure, flow quality, and calibration.",
    metaphor: "Finish the desk checklist, then raise difficulty.",
    unlock: "Full v1.0 loop",
    checkpoints: [
      "Finish this tutorial, then clear the 12 core Greek Sense Lab and Strategy Forge levels.",
      "For every mission, read Market Weather, build in Portfolio Builder, and check Payoff plus Scenario charts before running.",
      "During the run, use Delta hedge, Buy wing, and Risk Shield when the book leaves the mission limits.",
      "After each run, scrub Replay Panel and explain Delta, Gamma, Theta, Vega, cost, drawdown, and RV-IV effects.",
      "Before skew, calendar, event-vol, or vega-neutral missions, inspect Vol Surface Cartographer and vega buckets.",
      "Use Market Maker Arena to practice quote width, toxic flow, and inventory Delta/Vega control.",
      "Submit Probability Pit forecasts and track Average Brier instead of judging only P&L.",
      "Launch Challenge seed missions to create repeatable daily practice from the 100+ procedural pool.",
      "Beat Jane Street Trials after the core loop is stable, then save clean runs to the leaderboard.",
    ],
  },
];
